
// This file has been generated by the GUI designer. Do not modify.
namespace ooplab01
{
	public partial class MainWindow
	{
		private global::Gtk.Fixed fixed1;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Entry nameInput;
		
		private global::Gtk.Entry governmentFormInput;
		
		private global::Gtk.Entry squareInput;
		
		private global::Gtk.Button makeObjectButton;
		
		private global::Gtk.Button makeCopyButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget ooplab01.MainWindow
			this.Name = "ooplab01.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child ooplab01.MainWindow.Gtk.Container+ContainerChild
			this.fixed1 = new global::Gtk.Fixed ();
			this.fixed1.Name = "fixed1";
			this.fixed1.HasWindow = false;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Ваш клас - КРАЇНА");
			this.fixed1.Add (this.label1);
			global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label1]));
			w1.X = 109;
			w1.Y = 12;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Назва");
			this.fixed1.Add (this.label2);
			global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label2]));
			w2.X = 28;
			w2.Y = 56;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Площа");
			this.fixed1.Add (this.label4);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label4]));
			w3.X = 27;
			w3.Y = 122;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Форма правління");
			this.fixed1.Add (this.label3);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.label3]));
			w4.X = 27;
			w4.Y = 90;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.nameInput = new global::Gtk.Entry ();
			this.nameInput.CanFocus = true;
			this.nameInput.Name = "nameInput";
			this.nameInput.IsEditable = true;
			this.nameInput.InvisibleChar = '●';
			this.fixed1.Add (this.nameInput);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.nameInput]));
			w5.X = 190;
			w5.Y = 53;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.governmentFormInput = new global::Gtk.Entry ();
			this.governmentFormInput.CanFocus = true;
			this.governmentFormInput.Name = "governmentFormInput";
			this.governmentFormInput.IsEditable = true;
			this.governmentFormInput.InvisibleChar = '●';
			this.fixed1.Add (this.governmentFormInput);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.governmentFormInput]));
			w6.X = 190;
			w6.Y = 85;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.squareInput = new global::Gtk.Entry ();
			this.squareInput.CanFocus = true;
			this.squareInput.Name = "squareInput";
			this.squareInput.IsEditable = true;
			this.squareInput.InvisibleChar = '●';
			this.fixed1.Add (this.squareInput);
			global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.squareInput]));
			w7.X = 189;
			w7.Y = 117;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.makeObjectButton = new global::Gtk.Button ();
			this.makeObjectButton.CanFocus = true;
			this.makeObjectButton.Name = "makeObjectButton";
			this.makeObjectButton.UseUnderline = true;
			this.makeObjectButton.BorderWidth = ((uint)(3));
			this.makeObjectButton.Label = global::Mono.Unix.Catalog.GetString ("Make an object");
			this.fixed1.Add (this.makeObjectButton);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.makeObjectButton]));
			w8.X = 28;
			w8.Y = 155;
			// Container child fixed1.Gtk.Fixed+FixedChild
			this.makeCopyButton = new global::Gtk.Button ();
			this.makeCopyButton.CanFocus = true;
			this.makeCopyButton.Name = "makeCopyButton";
			this.makeCopyButton.UseUnderline = true;
			this.makeCopyButton.Label = global::Mono.Unix.Catalog.GetString ("Make object copy");
			this.fixed1.Add (this.makeCopyButton);
			global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.makeCopyButton]));
			w9.X = 170;
			w9.Y = 158;
			this.Add (this.fixed1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 416;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.makeObjectButton.Clicked += new global::System.EventHandler (this.OnMakeObjectClicked);
			this.makeCopyButton.Clicked += new global::System.EventHandler (this.OnMakeCopyButtonClicked);
		}
	}
}
